title: "Tofumelo - Receitas Vegan Fáceis e Deliciosas"
description: "Descubra as melhores receitas vegan para pequenos-almoços, almoços, jantares e sobremesas. Simples, saborosas e saudáveis."
baseurl: "" # the subpath of your site, e.g. /blog 
url: "https://tofumelo.pt" # the base hostname & protocol for your site

jekyll-sitemap:
  changefreq: "weekly"
  priority: "0.8"
  enable: true
  canonical: true


collections:
  authors:
    output: true
  chefs:
    output: true # Ensures the pages from the _chefs collection are generated
  pages:
    output: true

permalink: pretty 
markdown: kramdown

sass:
  sass_dir: assets/css/_sass
  style: compressed


defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default" # Applies the default layout for all pages in `_pages`
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author" # Applies the author layout to authors
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post" # Applies the post layout to blog posts
  - scope:
      path: ""
    values:
      layout: "default" # Catch-all default layout

plugins:
  - jekyll-sitemap
exclude:
  - chefs/bepureinside/
  - chefs/derek-sarno/
  - chefs/evagoodlife/
  - chefs/fitgreenmind/
  - chefs/greentastecuisine/
  - chefs/omeletes_sem_ovos/
  - chefs/tuga-vegetal/


